---
title: "Logistic"
author: "JLMR"
date: 2019-02-28T21:14:14-05:00
categories: ["R"]
tags: ["Logistic", "log(odds)", "glm"]
mathjax : true
menu:
  main:
    name: Logistic R
    weight: 15
---


```{r set-global-options, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = TRUE, 
                      cache = FALSE,
                      include = TRUE,
                      collapse = FALSE,
                      dependson = NULL,
                      engine = "R", # Chunks will always have R code, unless noted
                      error = FALSE)   


```



```{r silent-packages, echo = FALSE, eval = TRUE, message=FALSE, include = FALSE}
library(tidyverse)
library(ISLR)
library(foreign)
```



### Por qué el modelo de Regresión Logistica?

En los casos anteriores hemos considerado que nuestros datos son númericos (variables contínuas o discretas pero de naturaleza cuantitaiva).

Para el caso de el modelo de regresión logistica nos interesa hacer predicciones para  variables **categóricas**.  

Reponder preguntas como: Cual es 
