<!DOCTYPE html>
<html class="no-js" lang="en-us">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Logistic3</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
	<meta name="generator" content="Hugo 0.54.0" />
	<meta property="og:title" content="Logistic3" />
<meta property="og:description" content="Ejecicio estime un modelo de regresión logística considerando el siguiente escenario.
Se tienen una serie de características sociodemograficas (ej. sexo, edad, )incluidos marcadores clínicos para una muestra 297 individuos.
El objetivo es determinar la probabilidad de que la persona tenga un padecimiento cardiáco (heart disease).
La variable dependiente es hd con dos categorías: Healthy=0, o Unhealthy=1
A continuación la descripción de la información disponible y la codificación de las variables." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/post/2019-04-16-logistic3/" />
<meta property="article:published_time" content="2019-04-09T21:14:14-05:00"/>
<meta property="article:modified_time" content="2019-04-09T21:14:14-05:00"/>

	
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">
	<link rel="stylesheet" href="/css/style.css">
	<link rel="shortcut icon" href="/favicon.ico">
		
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-124338825-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container">
		<div class="logo">
			<a class="logo__link" href="/" title="Estadística II" rel="home">
				<div class="logo__title">Estadística II</div>
				<div class="logo__tagline">Semestre II MEP 2019</div>
			</a>
		</div>
		
<nav class="menu">
	<button class="menu__btn" aria-haspopup="true" aria-expanded="false" tabindex="0">
		<span class="menu__btn-title" tabindex="-1">Menu</span>
	</button>
	<ul class="menu__list">
		<li class="menu__item">
			<a class="menu__link" href="/about/">Maestría en estudios de población</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/syllabus/">Syllabus</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2015-07-23-rl/">Regresion Lineal</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2019-01-11-rl2/">RL-Simple</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2019-01-15-rl3/">RL-Modelo</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2019-01-25-rl4/">RL-Hipótesis</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2019-01-25-rl5/">RL-Muiltiple</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2019-02-05-rl6/">RL-Diagnóstico</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2019-20-01-rl7-models/">RL-Multiple Cross-Section</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2019-02-24-pca/">PCA</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/recursos-adicionales/">Recursos Adicionales</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2018-12-30-ejercicios/">Ejercicios</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2019-02-25-logistic/">Logistic R</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/post/2019-04-15-logistic2/">Logistic2 R</a>
		</li>
		<li class="menu__item menu__item--active">
			<a class="menu__link" href="/post/2019-04-16-logistic3/">Logistic3 R</a>
		</li>
	</ul>
</nav>

	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Logistic3</h1>
			<div class="post__meta meta">
<div class="meta__item-datetime meta__item">
	<svg class="meta__icon icon icon-time" width="16" height="14" viewBox="0 0 16 16"><path d="m8-.0000003c-4.4 0-8 3.6-8 8 0 4.4000003 3.6 8.0000003 8 8.0000003 4.4 0 8-3.6 8-8.0000003 0-4.4-3.6-8-8-8zm0 14.4000003c-3.52 0-6.4-2.88-6.4-6.4000003 0-3.52 2.88-6.4 6.4-6.4 3.52 0 6.4 2.88 6.4 6.4 0 3.5200003-2.88 6.4000003-6.4 6.4000003zm.4-10.4000003h-1.2v4.8l4.16 2.5600003.64-1.04-3.6-2.1600003z"/></svg>
	<time class="meta__text" datetime="2019-04-09T21:14:14">April 09, 2019</time>
</div>

<div class="meta__item-categories meta__item">
	<svg class="meta__icon icon icon-category" width="16" height="16" viewBox="0 0 16 16"><path d="m7 2l1 2h8v11h-16v-13z"/></svg>
	<span class="meta__text"><a class="meta__link" href="/categories/r" rel="category">R</a></span>
</div>
</div>
		</header><div class="content post__content clearfix">
			


<p>Ejecicio estime un modelo de regresión logística considerando el siguiente escenario.</p>
<p>Se tienen una serie de características sociodemograficas (ej. sexo, edad, )incluidos marcadores clínicos para una muestra 297 individuos.</p>
<p>El objetivo es determinar la probabilidad de que la persona tenga un padecimiento cardiáco (heart disease).</p>
<p>La variable dependiente es <strong>hd</strong> con dos categorías: Healthy=0, o Unhealthy=1</p>
<p>A continuación la descripción de la información disponible y la codificación de las variables.</p>
<p><strong>age</strong> variable contínua para edad.</p>
<p><strong>sexo</strong> 0 = Femenino, 1 = Masculino</p>
<p><strong>cp</strong> Dolor en pecho (chest pain)</p>
<p>1 = typical angina,</p>
<p>2 = atypical angina,</p>
<p>3 = non-anginal pain,</p>
<p>4 = asymptomatic</p>
<p><strong>trestbps</strong> Presión alterial. (resting blood pressure) (medida en mm Hg) (variable Contínua).</p>
<p><strong>ca</strong>, number of major vessels colored by fluoroscopy. (2-5) (Marcador bimétrico sobre daño arterial)</p>
<p><strong>thal</strong>, Short of thalium heart scan: A thallium heart scan is a test using a special camera and a small amount of radioactive substance injected into the bloodstream to make an image of the blood flow to the heart.</p>
<p>2 = normal (no cold spots)</p>
<p>3 = fixed defect (cold spots during rest and exercise)</p>
<p>4 = reversible defect (when cold spots only appear during exercise)</p>
<p><strong>hd</strong> Variable dependiente (diagnosis of heart disease): 0 if less than or equal to 50% diameter narrowing 1 if greater than 50% diameter narrowing</p>
<p><strong>Instruccones:</strong></p>
<p>Estime un modelo de regresión logistica simple para la variable padecimiento cardiaco (variable hd) considerando como variable independiente el <strong>sexo</strong> de la persona.</p>
<p>Determine el log del ratio de los momios <strong>log(odds ratio)</strong> indique su magnitud, dirección y sin son estadísticamente significativos al <span class="math inline">\(0.05\%\)</span>.</p>
<p><strong>Primero una observación básica de los datos </strong></p>
<pre class="r"><code>data&lt;-readRDS(&quot;heartd.rds&quot;)

names(data)</code></pre>
<pre><code>##  [1] &quot;age&quot;      &quot;sexo&quot;     &quot;cp&quot;       &quot;trestbps&quot; &quot;chol&quot;     &quot;fbs&quot;     
##  [7] &quot;restecg&quot;  &quot;thalach&quot;  &quot;exang&quot;    &quot;oldpeak&quot;  &quot;slope&quot;    &quot;ca&quot;      
## [13] &quot;thal&quot;     &quot;hd&quot;</code></pre>
<pre class="r"><code>glimpse(data)</code></pre>
<pre><code>## Observations: 297
## Variables: 14
## $ age      &lt;dbl&gt; 63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 4...
## $ sexo     &lt;chr&gt; &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M&quot;, &quot;F&quot;, &quot;M&quot;, &quot;F&quot;, &quot;F&quot;, &quot;M&quot;, &quot;M&quot;, &quot;M&quot;...
## $ cp       &lt;fct&gt; 1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3, 2, 4,...
## $ trestbps &lt;dbl&gt; 145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140...
## $ chol     &lt;dbl&gt; 233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192...
## $ fbs      &lt;fct&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,...
## $ restecg  &lt;fct&gt; 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0,...
## $ thalach  &lt;dbl&gt; 150, 108, 129, 187, 172, 178, 160, 163, 147, 155, 148...
## $ exang    &lt;fct&gt; 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,...
## $ oldpeak  &lt;dbl&gt; 2.3, 1.5, 2.6, 3.5, 1.4, 0.8, 3.6, 0.6, 1.4, 3.1, 0.4...
## $ slope    &lt;fct&gt; 3, 2, 2, 3, 1, 1, 3, 1, 2, 3, 2, 2, 2, 1, 1, 1, 3, 1,...
## $ ca       &lt;fct&gt; 2, 5, 4, 2, 2, 2, 4, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2,...
## $ thal     &lt;fct&gt; 3, 2, 4, 2, 2, 2, 2, 2, 4, 4, 3, 2, 3, 4, 4, 2, 4, 2,...
## $ hd       &lt;fct&gt; Healthy, Unhealthy, Unhealthy, Healthy, Healthy, Heal...</code></pre>
<pre class="r"><code>xtabs(~ hd + sexo, data=data)</code></pre>
<pre><code>##            sexo
## hd            F   M
##   Healthy    71  89
##   Unhealthy  25 112</code></pre>
<p>Note que tenemos aparentemente un mayor problema para el sexo masculino.</p>
<pre class="r"><code>logistic &lt;- glm(hd ~ sexo, data=data, family=&quot;binomial&quot;)

summary(logistic)</code></pre>
<pre><code>## 
## Call:
## glm(formula = hd ~ sexo, family = &quot;binomial&quot;, data = data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2765  -1.2765  -0.7768   1.0815   1.6404  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.0438     0.2326  -4.488 7.18e-06 ***
## sexoM         1.2737     0.2725   4.674 2.95e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 409.95  on 296  degrees of freedom
## Residual deviance: 386.12  on 295  degrees of freedom
## AIC: 390.12
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>male.log.odds.ratio &lt;- log((112 / 89) / (25/71))
male.log.odds.ratio</code></pre>
<pre><code>## [1] 1.273667</code></pre>
<p>Por su parte la prueba de Wald toma el cociente entre el log (odd ratio ) y la desviación estandar de la muesta <strong>SE</strong> en este caso <span class="math inline">\(1.2737/0.2725=4.674\)</span>. Este valor corresponde al estadístico de prueba <strong>Z</strong>.</p>
<pre class="r"><code>1.2737/0.2725</code></pre>
<pre><code>## [1] 4.674128</code></pre>
<p>Lo que inidica cuantas desviaciones estándar el <strong>log(odd ratio)</strong> está de cero. Considerando lo que ya sabemos sobre prueba de hipótesis un valor de peruba (<strong>Z</strong> en este caso) mayor a 1.96 tendrá un <em>p-value&lt;0.05</em> y por lo tanto será estadísticamente significativo. En este caso el estadístico de prueba <strong>Z=4.674</strong> y tiene un p-value de 0.00000295.</p>
<p>La variable <strong>sexo</strong> tiene una relación estadísticamente significativa con la variable dependiente (padecimiento cardiáco).</p>
<p>Donde <strong>(Intercept)</strong> -1.0438 es el log (odds) para la categoría base en este caso <strong>Mujer</strong> y el coeficiente <strong>sexM=</strong> 1.2737 es el log(odds ratio) cuando el paciente es hombre.</p>
<p>Interpretación: Para los Hombres se incrementa el logaritmo en el ratio de Momios de tener el pedecimiento, lo que se traduce en una <strong>proabilidad</strong> más elevada para un paciente del sexo masculino. <strong>NOTE</strong> que directamente el coeficiente estimado <strong>NO</strong> es la probabilidad todavía, aunque dado ese resultado sabemos que las probabilidades de tener el padecimiento son mayores par los hombres respecto a las mujeres.</p>
<p>Para determinar las <strong>probabilidades</strong> a partir del logaritmo del cociente de momios (coef. de nuestro modelo), extraemos las predicciones (<em>fitted.values</em>) que estan almacenadas como parte de los resultados del modelo. La siguiente estimación muestra el cálculo.</p>
<div id="prediccion-de-probabilidades." class="section level5">
<h5>Predicción de probabilidades.</h5>
<pre class="r"><code>predic&lt;- data.frame(
  prob.hd=logistic$fitted.values,
  sexo=data$sexo)

glimpse(predic)</code></pre>
<pre><code>## Observations: 297
## Variables: 2
## $ prob.hd &lt;dbl&gt; 0.5572139, 0.5572139, 0.5572139, 0.5572139, 0.2604167,...
## $ sexo    &lt;fct&gt; M, M, M, M, F, M, F, F, M, M, M, F, M, M, M, M, M, M, ...</code></pre>
<p>Note que la probabilidad de tener el padecimiento para un individuo del sexo masculino es <span class="math inline">\(= 0.55&gt;0.26\)</span> a la de una mujer.</p>
</div>
<div id="graficamos-las-probabilidades." class="section level5">
<h5>Graficamos las probabilidades.</h5>
<pre class="r"><code>ggplot(predic, aes(sexo,prob.hd, size=sexo)) +
  geom_point(aes(color=sexo))+
  xlab(&quot;Sexo&quot;) +
  ylab(&quot;Pr padecimiento cardiáco&quot;)+
  theme_classic()+
  theme(legend.position = &quot;none&quot;)+
  scale_color_manual(values =c(&quot;deeppink&quot;,&quot;deepskyblue3&quot;))+
  labs(x=&quot;Sexo&quot;)</code></pre>
<p><img src="/post/2019-04-16-Logistic3_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="estmacion-rl-multiple-mas-de-una-variable-independiente." class="section level4">
<h4>Estmación RL Multiple Más de una variable independiente.)</h4>
<div id="ejercicio-2" class="section level5">
<h5>Ejercicio 2</h5>
<p>Estime el modelo de regresión logística para la siguiente especificación:</p>
<p><span class="math display">\[\hat{p}(X)=\frac{e^{\beta_0+\beta_1age+\beta_2sexo+\beta_3cp+\beta_4ca+\beta_5thal}}{1+e^{\beta_0+\beta_1age+\beta_2sexo+\beta_3cp+\beta_4ca+\beta_5thal}}\]</span> a) Indique el valor del cociente de momios para las variables independientes del modelo. ¿Qué variables son estadísticamente significativas? ¿Cual es el nivel de significancia para la variable sexo? Argumente sobre la rezón de este resultado.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Genera la predicción de las probabilidades de que los individuos tengan padecimiento cardiáco, grafique.</li>
</ol>
<pre class="r"><code>logistic2 &lt;- glm(hd ~age+sexo+cp+ca+thal, data=data, family=&quot;binomial&quot;)
summary(logistic2)</code></pre>
<pre><code>## 
## Call:
## glm(formula = hd ~ age + sexo + cp + ca + thal, family = &quot;binomial&quot;, 
##     data = data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.6957  -0.6072  -0.2197   0.6045   2.4424  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -4.47870    1.35653  -3.302 0.000961 ***
## age          0.02279    0.02050   1.111 0.266376    
## sexoM        0.89501    0.42478   2.107 0.035117 *  
## cp2         -0.05905    0.66069  -0.089 0.928779    
## cp3         -0.39502    0.62134  -0.636 0.524936    
## cp4          1.83340    0.56271   3.258 0.001121 ** 
## ca3          1.85376    0.43779   4.234 2.29e-05 ***
## ca4          2.32602    0.59820   3.888 0.000101 ***
## ca5          2.24263    0.78411   2.860 0.004235 ** 
## thal3        0.99575    0.66700   1.493 0.135466    
## thal4        1.92956    0.38275   5.041 4.62e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 409.95  on 296  degrees of freedom
## Residual deviance: 225.49  on 286  degrees of freedom
## AIC: 247.49
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Note que la variable <strong>age</strong> no es estadisticamente significativa. Un resultado contraintuitivo. Sin embargo, observando la distribución de los datos notamos que la mayoria de las personas de la muestra son de edad avanzada (ej. mediana=56 años).</p>
<pre class="r"><code>summary(data$age)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   29.00   48.00   56.00   54.54   61.00   77.00</code></pre>
<p>Note un <strong>Akaike Information Criterion</strong> mucho más pequeño para este modelo que incluye un conjunto de variables explicativas mayor.</p>
<p>Generalmente el<strong>AIC</strong> es un estadístico que comparamos entre especificaciones distintas de modelos para seleccionar el modelo final (ej. AIC menor).</p>
<pre class="r"><code>pred&lt;- data.frame(
  pr=logistic2$fitted.values,
  hd=data$hd)

pred&lt;-arrange(pred,pr)%&gt;%
  mutate(id=1:nrow(pred))


ggplot(pred, aes(id, pr)) +
  geom_point(aes(color=hd), 
  alpha=1, shape=21) +
  xlab(&quot;Individuos&quot;) +
  ylab(&quot;Pr(de tener pad. cardíaco)&quot;)+
  theme_classic()+
  scale_color_manual(values =c(&quot;darkgreen&quot;,&quot;orange&quot;))+
  labs(color=&quot;Status&quot;)</code></pre>
<p><img src="/post/2019-04-16-Logistic3_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>En una primera inspección general, el hecho de que la mayoria de los individuos con el padecimiento cardiáco se ubiquen con una pr&gt;.5, indica que el modelo de hecho funciona bien, sin embargo, para evaluar <strong>la precisión del modelo</strong> es necesario hacer el <strong>proceso de validación</strong> (ej. determinar cuantos casos que se predicen en la categoría 1, de hecho pertenecen a esa categoría).</p>
<p>Dissclaimer: “Some of the figures in this presentation are taken from”An Introduction to Statistical Learning, with applications in R&quot; (Springer, 2013) with permission from the authors: G. James, D. Witten, T. Hastie and R. Tibshirani &quot;</p>
</div>
</div>

		</div>
		
<div class="post__tags tags clearfix">
	<svg class="icon icon-tag" width="16" height="16" viewBox="0 0 16 16"><path d="M16 9.5c0 .373-.24.74-.5 1l-5 5c-.275.26-.634.5-1 .5-.373 0-.74-.24-1-.5L1 8a2.853 2.853 0 0 1-.7-1C.113 6.55 0 5.973 0 5.6V1.4C0 1.034.134.669.401.401.67.134 1.034 0 1.4 0h4.2c.373 0 .95.113 1.4.3.45.187.732.432 1 .7l7.5 7.502c.26.274.5.632.5.998zM3.5 5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/></svg>
	<ul class="tags__list">
		<li class="tags__item"><a class="tags__link btn" href="/tags/logistic/" rel="tag">Logistic</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/logodds/" rel="tag">log(odds)</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/glm/" rel="tag">glm</a></li>
	</ul>
</div>
	</article>
</main>

<div class="authorbox clearfix">
	<figure class="authorbox__avatar">
		<img alt="José Luis Manzanares Rivera avatar" src="/img/aavatar.jpg" class="avatar" height="90" width="90">
	</figure>
	<div class="authorbox__header">
		<span class="authorbox__name">About José Luis Manzanares Rivera</span>
	</div>
	<div class="authorbox__description">
		José Luis is a data scientist. He is currently conducting applied research at El Colegio de la Frontera Norte.
	</div>
</div>

<nav class="post-nav flex">
	<div class="post-nav__item post-nav__item--prev">
		<a class="post-nav__link" href="/post/2019-04-15-logistic2/" rel="prev"><span class="post-nav__caption">«&thinsp;Previous</span><p class="post-nav__post-title">Logistic2</p></a>
	</div>
</nav>

<section class="comments">
	<div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "4insight" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</section>


			</div>
			<aside class="sidebar"><div class="widget-search widget">
	<form class="widget-search__form" role="search" method="get" action="https://google.com/search">
		<label>
			<input class="widget-search__field" type="search" placeholder="SEARCH..." value="" name="q" aria-label="SEARCH...">
		</label>
		<input class="widget-search__submit" type="submit" value="Search">
		<input type="hidden" name="sitesearch" value="/" />
	</form>
</div>
<div class="widget-recent widget">
	<h4 class="widget__title">Recent Posts</h4>
	<div class="widget__content">
		<ul class="widget__list">
			<li class="widget__item"><a class="widget__link" href="/post/2019-04-16-logistic3/">Logistic3</a></li>
			<li class="widget__item"><a class="widget__link" href="/post/2019-04-15-logistic2/">Logistic2</a></li>
			<li class="widget__item"><a class="widget__link" href="/post/2019-02-25-logistic/">Logistic</a></li>
			<li class="widget__item"><a class="widget__link" href="/post/2019-02-05-rl6/">RL-Diagnóstico</a></li>
			<li class="widget__item"><a class="widget__link" href="/post/2019-02-24-pca/">PCA</a></li>
		</ul>
	</div>
</div>
<div class="widget-categories widget">
	<h4 class="widget__title">Categories</h4>
	<div class="widget__content">
		<ul class="widget__list">
			<li class="widget__item"><a class="widget__link" href="/categories/development">Development</a></li>
			<li class="widget__item"><a class="widget__link" href="/categories/r">R</a></li>
		</ul>
	</div>
</div>
<div class="widget-taglist widget">
	<h4 class="widget__title">Tags</h4>
	<div class="widget__content">
		<a class="widget-taglist__link widget__link btn" href="/tags/basic-elements" title="Basic elements">Basic elements</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/classification" title="Classification">Classification</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/clustering" title="Clustering">Clustering</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/css" title="Css">Css</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/glm" title="Glm">Glm</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/html" title="Html">Html</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/logistic" title="Logistic">Logistic</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/logodds" title="Logodds">Logodds</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/mco" title="Mco">Mco</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/pca" title="Pca">Pca</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/regresi%c3%b3n-lineal" title="Regresión lineal">Regresión lineal</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/regression" title="Regression">Regression</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/unsupervised-statistical-learning" title="Unsupervised statistical learning">Unsupervised statistical learning</a>
	</div>
</div>
</aside>
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2019 Estadística II.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
	</div>
<script async defer src="/js/menu.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML" async></script>
</body>
</html>